name: dep-installer-job-docker

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-dep-install-job:
    name: Build dep installer docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build dep-installer-job-docker
        run: make dep-installer-job-docker

      - name: Push to Github packages
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          GITHUB_IMAGE_NAME: ghcr.io/nocalhost/nocalhost/dep-installer-job
        run: |
          docker tag dep-installer-job:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}

      - name: Push latest to Github packages
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          GITHUB_IMAGE_NAME: ghcr.io/nocalhost/nocalhost/dep-installer-job
        run: |
          docker tag dep-installer-job:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:latest
          docker push ${GITHUB_IMAGE_NAME}:latest
