name: nhctl

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:

  build-nhctl-windows-linux:
    name: Build windows linux nhctl
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Build
        run: |
          export GITHUB_ACTION=true
          make nhctl-linux
          make nhctl-windows
          make nhctl-linux-arm64

  build-nhctl-macos:
    name: Build macos nhctl
    runs-on: macos-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Build
        run: |
          export GITHUB_ACTION=true
          make nhctl-osx
          make nhctl-osx-arm64
